name: static-mpv
version: 0.1.0.0
synopsis: static exe with mpv
description: static exe with mpv
license: OtherLicense
license-file: LICENSE
author: "Torsten Schmits"
maintainer: "tek@tryp.io"
copyright: "2020 Torsten Schmits"
category: Debug
build-type: Simple

dependencies:
- base >= 4.7 && < 5

extra-libraries:
  - mpv

build-tools:
  c2hs:c2hs

executables:
 static-mpv:
  main: Main.hs
  source-dirs: app
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
